# Generated by Django 4.2.7 on 2023-12-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('character_id', models.PositiveIntegerField(db_column='Character_id', primary_key=True, serialize=False)),
                ('character_name', models.CharField(blank=True, db_column='Character_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'characters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.PositiveBigIntegerField(db_column='Script_id', primary_key=True, serialize=False)),
                ('script_name', models.CharField(blank=True, db_column='Script_name', max_length=255, null=True)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=255, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=255, null=True)),
                ('score', models.DecimalField(blank=True, db_column='Score', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'script',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('script', models.OneToOneField(db_column='Script_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='work.script')),
                ('comment_id', models.PositiveBigIntegerField(db_column='Comment_id')),
                ('comment_time', models.DateField(blank=True, db_column='Comment_time', null=True)),
                ('commentator', models.CharField(blank=True, db_column='Commentator', max_length=255, null=True)),
                ('comment_content', models.TextField(blank=True, db_column='Comment_content', null=True)),
                ('comment_title', models.CharField(blank=True, db_column='Comment_title', max_length=255, null=True)),
                ('comment_type', models.CharField(blank=True, db_column='Comment_type', max_length=255, null=True)),
                ('positive_score', models.DecimalField(blank=True, db_column='Positive_score', decimal_places=3, max_digits=5, null=True)),
                ('negative_score', models.DecimalField(blank=True, db_column='Negative_score', decimal_places=3, max_digits=5, null=True)),
                ('neutral_score', models.DecimalField(blank=True, db_column='Neutral_score', decimal_places=3, max_digits=5, null=True)),
                ('compound_score', models.DecimalField(blank=True, db_column='Compound_score', decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Highfreqword',
            fields=[
                ('script', models.OneToOneField(db_column='Script_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='work.script')),
                ('word', models.CharField(blank=True, db_column='Word', max_length=255, null=True)),
                ('word_id', models.PositiveIntegerField(db_column='Word_id')),
            ],
            options={
                'db_table': 'highfreqword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('script', models.OneToOneField(db_column='Script_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='work.script')),
                ('interaction_id', models.PositiveIntegerField(db_column='Interaction_id')),
                ('interaction_freqnum', models.PositiveBigIntegerField(blank=True, db_column='Interaction_freqnum', null=True)),
                ('relation', models.CharField(blank=True, db_column='Relation', max_length=255, null=True)),
            ],
            options={
                'db_table': 'interaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('script', models.OneToOneField(db_column='Script_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='work.script')),
                ('scene_id', models.PositiveIntegerField(db_column='Scene_id')),
                ('scene_content', models.TextField(blank=True, db_column='Scene_content', null=True)),
                ('scene_name', models.CharField(blank=True, db_column='Scene_name', max_length=255, null=True)),
                ('scene_time', models.DateField(blank=True, db_column='Scene_time', null=True)),
            ],
            options={
                'db_table': 'scene',
                'managed': False,
            },
        ),
    ]
