# Generated by Django 4.2.7 on 2023-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmoAnalysis',
            fields=[
                ('ea_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expert_result', models.TextField(blank=True, null=True)),
                ('user_result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emo_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkEmoAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expert_result', models.TextField(blank=True, null=True)),
                ('user_result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'work_emo_analysis',
                'managed': False,
            },
        ),
    ]
