# Generated by Django 4.2.7 on 2023-12-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_emoanalysis_workemoanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkEmoAnalysis',
        ),
    ]
