# Generated by Django 4.2.7 on 2023-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmoAnalysis',
            fields=[
                ('ea_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expert_result', models.TextField(blank=True, null=True)),
                ('user_result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emo_analysis',
                'managed': False,
            },
        ),
    ]
